
language: php

sudo: false

git:
  depth: 2

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly

before_script:
  - php --version
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry mysql -e 'CREATE DATABASE mysql_test;'
  - travis_retry mysql -e 'USE mysql_test; CREATE TABLE session_data ( session_id varchar(128) NOT NULL default "", hash varchar(128) NOT NULL default "", session_data blob NOT NULL, session_expire int(11) NOT NULL default "0", PRIMARY KEY session_id (`session_id`), KEY hash (`hash`), KEY session_expire (`session_expire`), KEY select_helper_index (`session_id`, `hash`, `session_expire`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;'
  - travis_retry mysql -e 'USE mysql_test; CREATE TABLE lock_data ( lock_hash varchar(128) NOT NULL, lock_time INT(11) UNSIGNED NOT NULL, PRIMARY KEY lock_hash (`lock_hash`), KEY lock_time (`lock_time`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;'
  - travis_retry composer self-update
  - travis_retry composer require satooshi/php-coveralls:1.0.0
  - travis_retry composer install --no-interaction --prefer-source
  - composer dump-autoload -o

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - bash <(curl -s https://codecov.io/bash)
